In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("orders.csv")

country_arr = df["country"].to_numpy()

cats, inv = np.unique(country_arr, return_inverse=True)

one_hot = np.eye(len(cats), dtype=int)[inv]

print("Country category:")
print(cats)

print("Country one-hot:")
print(one_hot)

Country category:
['DE' 'ES' 'FR' 'IE' 'IT' 'NL' 'PL' 'PT' 'SE' 'UK']
Country one-hot:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]]
