In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("sample_orders.csv")

country_arr = df["country"].to_numpy()

cats, inv = np.unique(country_arr, return_inverse=True)
one_hot = np.eye(len(cats), dtype=int)[inv]

print("=== One-hot country ===")
print("cats:")
print(cats)

print("one_hot:")
print(one_hot)

quantity_arr = df["quantity"].to_numpy()
price_arr = df["price_each"].to_numpy()

corr_quantity_price = np.corrcoef(quantity_arr, price_arr)[0, 1]

print("=== Correlation quantity vs price_each ===")
print(corr_quantity_price)
print(round(corr_quantity_price, 2))

quartiles = np.percentile(price_arr, [25, 50, 75])
price_bucket = np.digitize(price_arr, quartiles, right=True) + 1

print("=== Quartiles ===")
print(quartiles)

print("=== Price buckets ===")
print(price_bucket)

df["price_bucket"] = price_bucket

print(df[["price_each", "price_bucket"]].head())

=== One-hot country ===
cats:
['France' 'Germany' 'Ireland' 'Italy' 'Netherlands' 'Poland' 'Portugal'
 'Spain' 'Sweden' 'United Kingdom']
one_hot:
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
=== Correlation quantity vs price_each ===
-0.03130741044620734
-0.03
=== Quartiles ===
[ 9.99 16.99 29.99]
=== Price buckets ===
[2 4 3 1 2 1 4 4 3 4 3 1 4 4 4 3 4 2 3 1 1 1 1 1 3 2 4 2 4 4 3 3 1 1 3 2 1
 3 4 3 1 4 2 4 1 1 2 4 3 4 1 4 1 3 1 3 1 4 3 2 2 3 2 4 3 4 4 3 4 2 3 4 2 3
 3 3 4 4 1 2 2 3 3 1 2 4 2 4 4 2 2 2 1 2 1 4 4 4 2 1 3 4 3 1 2 3 1 2 2 2 4
 2 1 3 1 1 2 4 4 1 1 2 2 1 1 2 4 4 2 2 3 3 2 3 4 3 2 1 2 2 3 2 2 2 3 4 1 2
 3 4 4 1 3 3 2 1 2 3 4 4 4 1 2 2 3 2 1 4 4 3 2 3 3 1 1 2 4 2 2 1 1 1 2 4 3
 1 4 1 3 2 1 3 3 4 3 3 2 1 1 2 1 4 2 3 1 1 2 2 3 2 1 3 4 1 3 4 3 2 1 1 3 1
 3 2 3 1 2 4 1 1 3 4 2 3 3 2 3 2 3 2 4 1 2 2 3 4 4 3 1 2 1 4 2 3 4 3 3 1 3
 2 1 1 4 2 2 3 4 3 2 1 2 3 3 4 3 1 1 2 4 4 1 3 2 1 2 3 1 1 3 3 3 3 4 3 2 1
 3 